# -*- coding: utf-8 -*-
"""python practice.ipynb

Automatically generated by Colab.


variables
loops
operators
functions
comments
if else
switch
for each
arrays
dictonaries
sets
lists
tuple
import
"""

name="amara"
sign='3'
#i am comment
no=2
point=0
check=True
if check==True:
  for a in range(1,5,1):
   print("yes for loop")
else:
  while check==True:
    print("inside while of else block")
    for b in range(1,5,1):
      check=not check
def myfun(var):
  sum=var+3
  return sum
if sign=='3':
  r=myfun(no)
  print("THe value of no now is five :",r)
if point==2.4:
  print("yes")
elif point==3.5:
  print("no")
elif point==0:
  print("no/yes")
else:
  print("nothing")

"""***now data collections***"""

#list
l=['a',2.1,True]
#print(l)
l[1]=44
print(l[2])
#tuple
t=('a',2.1,False)
#tuple[0]=67
#set
s={1,5,5}
print(s)
#dictionary
d={1:'d',2:'f'}
print(d[1])
d.pop(2)
print(d.get(1))
